name: Dependabot Jira Automation
on:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: write   # allow editing PR (e.g., adding labels)

jobs:
  create_jira_issue:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check if this is a security update
        id: security_check
        run: |
          # Write the PR title and body into a temporary file
          echo "${{ github.event.pull_request.title }}" > pr_content.txt
          echo "${{ github.event.pull_request.body }}" >> pr_content.txt

          # Search the file for security keywords
          if grep -qi -e "CVE-" -e "GHSA" -e "security" pr_content.txt; then
            echo "SECURITY_PR=true" >> $GITHUB_ENV
          else
            echo "SECURITY_PR=false" >> $GITHUB_ENV
          fi

      - name: Label PR as security
        if: ${{ env.SECURITY_PR == 'true' }}
        run: |
          SUMMARY="Dependabot - ${{ github.event.pull_request.title }}"
          DESCRIPTION="## Description\n${{ github.event.pull_request.html_url }}"
          JIRA_PROJECT_KEY="BCT"

          curl -X POST \
            -H "Content-Type: application/json" \
            -u "${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
            -d "{
                  \"fields\": {
                    \"project\": {
                      \"key\": \"${JIRA_PROJECT_KEY}\"
                    },
                    \"summary\": \"${SUMMARY}\",
                    \"issuetype\": { \"name\": \"Task\" },
                    \"labels\": [\"vulnerability\"],
                    \"description\": \"${DESCRIPTION}\"
                  }
                }" \
            "${{ secrets.JIRA_BASE_URL }}/rest/api/2/issue"
